### PR TITLE
Added magnet torrent link support

### PR DESCRIPTION
**Pull request by gtuk**
You can now add a magnet link to search field and play it

### CODE REVIEW

**Comment by Japoilski** [comment]
cool!

**Comment by gtuk** [comment]
Are you going to pull it in the master or should the implementation be better?

**Comment by Japoilski** [comment]
I'm currently working in the ui branch. Everything is changing :S 
When I finish (end of the day or tomorrow :P) maybe you can re-implement the feature in this branch then we can merge into master?

**Comment by gtuk** [comment]
Ok sounds great. Let me know if you are finished then i will checkout the ui branch an i will reimplement it

**Comment by Japoilski** [comment]
Awesome :smile: 
New interface - > #33

**Comment by gtuk** [comment]
So here is my new pull request for the ui branch #46 
The package.json file seems not be up to date in your ui branch. 
Dependencies for the iconv-lite and jschardet node modules are missing
I didn't fix it

**Comment by Japoilski** [comment]
Your to fast for me :smile: I didn't push all my code yet.

**Comment by gtuk** [comment]
:-D ok sorry. I opened another pull request for this story(my previous comment here) Hope you can use it  later. If not let me know

**Comment by Japoilski** [comment]
Re-implement it in the master branch and I will merge automatically.
Thanks!

**Pull request closed without merging**
